name:  Deploy Web App using Terraform

on:
  workflow_dispatch:
    inputs:
      sites_markharrisonTF_name:
        description: "Enter the name of the App Service"
        required: true

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform Azure Deployment'
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Log in to Azure using the Azure CLI
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Validate Terraform configuration
    - name: Terraform Validate
      run: terraform validate

    # Format Terraform configuration files
    - name: Terraform Format
      run: terraform fmt -check

    # Generate a Terraform execution plan
    - name: Terraform Plan
      run: terraform plan -input=false -var "sites_markharrisonTF_name=${{ github.event.inputs.sites_markharrisonTF_name }}"

    # Apply the Terraform configuration to deploy resources to Azure
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
      run: terraform apply -auto-approve -input=false -var "sites_markharrisonTF_name=${{ github.event.inputs.sites_markharrisonTF_name }}"
