name: Deploy Web App using Terraform and OIDC

on:
  workflow_dispatch:
    inputs:
      sites_markharrisonTF_name:
        description: "Enter the name of the App Service"
        required: true

permissions:
  id-token: write    
  contents: read     
  

jobs:
  terraform:
    name: 'Terraform Azure Deployment'
    environment: 'production'
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Log in to Azure using the Azure CLI
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}   
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}   
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  
          enable-AzPSSession: true

      # Install the latest version of Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate

      # Apply the Terraform configuration to deploy resources to Azure
      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve -input=false -var "sites_markharrisonTF_name=${{ github.event.inputs.sites_markharrisonTF_name }}"
