name: Deploy Web App using ARM and OIDC

on:
  workflow_dispatch:
    inputs:
      sites_markharrisonTF_name:
        description: "Enter the value for sites_markharrisonTF_name"
        required: true

permissions:
  id-token: write    
  contents: read     
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 'production'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}   
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}   
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  
        enable-AzPSSession: true

    - name: Deploy ARM template
      run: |
        az deployment group create \
          --resource-group TFDeploy-rg \
          --template-file arm.json \
          --parameters sites_markharrisonTF_name=${{ github.event.inputs.sites_markharrisonTF_name }}
          
